apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - image: tyk-auth-golang-grpc-plugin:latest
        imagePullPolicy: IfNotPresent
        name: grpc
        ports:
        - containerPort: 5000