apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: Always
        name: mongo
        command: ["mongod", "--smallfiles"]
        ports:
        - containerPort: 27017